server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    loadbalancer:
      ribbon:
        enable: true

  application:
    name: court-service
appDescription: "Pragma Powerup"
appVersion: "1.0.0"
